# Generated by Django 3.2.13 on 2022-07-07 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artprints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('categories',),
            },
        ),
        migrations.AddField(
            model_name='artprint',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='artprints.category'),
            preserve_default=False,
        ),
    ]
