# Generated by Django 3.2.13 on 2022-07-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artprints', '0003_artprint_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artprint',
            name='approved',
        ),
    ]
